<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QHTT137" failures="2" tests="14" name="dsalgo-linkedlistTestintro" time="79.492" errors="0" timestamp="08 Nov 2021 22:50:43 GMT">
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="@AfterTest afterTest" time="0.001">
    <failure type="org.openqa.selenium.NoSuchSessionException" message="Session ID is null. Using WebDriver after calling quit()?
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-QHTT137&amp;apos;, ip: &amp;apos;192.168.1.80&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;15.0.2&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-QHTT137', ip: '192.168.1.80', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:442)
at com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test.afterTest(linkedlist_Introduction_Test.java:252)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist" name="linkedlist_testcase1" time="3.776"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist" name="linkedlist_testcase2" time="11.912"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist" name="linkedlist_testcase3" time="3.612"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist" name="linkedlist_testcase4" time="2.363">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.numpy_ninja.dsalgo.tests.linkedlist.linkedlist_testcase4(linkedlist.java:105)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- linkedlist_testcase4 -->
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="linkedlist_Introduction_testcase1" time="2.365"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="linkedlist_Introduction_testcase2" time="8.38"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="linkedlist_Introduction_testcase3" time="4.482"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="linkedlist_Introduction_testcase4" time="2.407"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="linkedlist_Introduction_testcase5" time="2.139"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="linkedlist_Introduction_testcase6" time="3.19">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test.linkedlist_Introduction_testcase6(linkedlist_Introduction_Test.java:166)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- linkedlist_Introduction_testcase6 -->
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="linkedlist_Introduction_testcase7" time="8.31"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="linkedlist_Introduction_testcase8" time="8.263"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="linkedlist_Introduction_testcase9" time="1.584"/>
  <testcase classname="com.numpy_ninja.dsalgo.tests.linkedlist_Introduction_Test" name="linkedlist_Introduction_testcase10" time="3.466"/>
</testsuite> <!-- dsalgo-linkedlistTestintro -->
